### ISSUE TITLE
Change how albums are sorted

### ISSUE THREAD

**Issue by DWW256** [SvDvorak/BandcampMultitagSearch#11]
I'm not sure, but I'm guessing the sorting method CampExplorer uses is "new and notable."  But being able to sort by "best selling" would be nice too.  Not sure if this is possible, but it sure would be helpful.

**Comment by SvDvorak** [comment]
I've thought about this before so since this is [very similar to my previous issue](https://github.com/SvDvorak/CampExplorer/issues/2) I'll just close this one and refer to the other one. Currently development of CampExplorer is on ice (I don't have the time really) so we'll see if it gets implemented in the future.
