### ISSUE TITLE
search never ends (spinner keeps spinning with "retrying..." without explanation)

### ISSUE THREAD

**Issue by lestephane** [SvDvorak/BandcampMultitagSearch#9]
My second attempt at running `docker-compose up` went further, but I'm now still unable to search.
It refuses to serve requests despite there being 13GB available on my disk.

![image](https://user-images.githubusercontent.com/5460884/105572951-d6642e80-5d62-11eb-8606-d375cff3f9a8.png)

I still want to try this locally, are there command-line flags I could use to:

- Ignore the low disk space condition
- Get more information about errors in the web page itself (for example: "Disk space is low") 

Here are the log messages:
[log.txt.gz](https://github.com/SvDvorak/CampExplorer/files/5859893/log.txt.gz)

**Comment by SvDvorak** [comment]
Sorry again for a slow response, I forgot to answer your question. After a quick google I found that [ElasticSearch has a disk space threshold](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/disk-allocator.html) so it seems like it's not starting the database because the disk is 95% full.
In the backend/database/elasticsearch.yml file add this to the end and from what I understand in the documentation it should disable the disk space threshold.
`cluster.routing.allocation.disk.threshold_enabled: false`
I haven't tested this myself though.
